<h1>Notebook para Pseudomonas </h1>

In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import hamming
import gudhi as gd
import seaborn as sns
from statistics import mode
import multiprocessing
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import gudhi as gd
# from scipy.spatial.distance import hamming
import plotly.graph_objs as go
import networkx as nx
import plotly.graph_objects as go
import plotly.io as pio
from networkx.utils import not_implemented_for, pairwise
from concurrent.futures import ThreadPoolExecutor, as_completed
import plotly
import plotly.express as px
from module_functions import *

<h2>Se extrae la información </h2>

In [2]:
info=pd.read_csv('data/pscpPseudoPrueba.blast',sep='\t',header=None)
names=pd.read_csv('data/Pseudomonas.ids',sep='\t',dtype='object',header=None)

<h2>Se crean los data frames</h2>

In [3]:
df_by_pathway,df_by_pathway_drop_duplicate,representative_genomes=get_df_by_pathway(info)

In [4]:
print('n genomas:',len(df_by_pathway['3PGA_AMINOACIDS'].index))
cont=0
cont2=0
for i,j in df_by_pathway.items():
    cont2+=len(j.columns)
    cont+=1
    print(i)
print('n rutas',cont)
print('n genes',cont2)

n genomas: 216
R5P_AMINOACIDS
Glycolysis
E4P_AMINO_ACIDS
OXALACETATE_AMINOACIDS
TCA
ALPHAKETOGLUTARATE_AMINOACIDS
polyketide
3PGA_AMINOACIDS
PYR_THR_AA
calcium-dependent-antibiotic
n rutas 10
n genes 45

<h2> Se crea el complejo simplicial</h2>

In [5]:
complex_pathways=get_complex_by_pathways(df_by_pathway_drop_duplicate)

In [8]:
complex_pathways['R5P_AMINOACIDS']
for i in complex_pathways.keys():
    contador=0
    for j in complex_pathways[i][0]:
        if j[0]==1:
            contador+=1
    print(i,contador)

R5P_AMINOACIDS 8
Glycolysis 2
E4P_AMINO_ACIDS 6
OXALACETATE_AMINOACIDS 54
TCA 4
ALPHAKETOGLUTARATE_AMINOACIDS 46
polyketide 0
3PGA_AMINOACIDS 9
PYR_THR_AA 51
calcium-dependent-antibiotic 0

In [6]:
#plot_all_bar_code_pathways(complex_pathways)

<h2>Se buscan los uno hoyos</h2>

In [7]:
holes_no_names,holes_with_names,holes_per_filt_lvl=get_holes_by_pathways(complex_pathways,df_by_pathway_drop_duplicate)

se buscan ciclos en el tiempo 2.0 para R5P_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Glycolysis
Se encontró el ciclo [4, 5, 2, 0] en el tiempo 1.0 para Glycolysis
Se encontró el ciclo [3, 1, 2, 0] en el tiempo 1.0 para Glycolysis
Terminó la ruta  Glycolysis
se buscan ciclos en el tiempo 2.0 para E4P_AMINO_ACIDS
se buscan ciclos en el tiempo 2.0 para OXALACETATE_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para TCA
se buscan ciclos en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para 3PGA_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [9, 12, 7, 2] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [5, 14, 2, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [24, 15, 3, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [24, 23, 8, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [8, 25, 3, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [2, 10, 1, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [4, 9, 2, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [5, 6, 3, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Terminó la ruta  R5P_AMINOACIDS
Se encontró el ciclo [8, 7, 6, 0] en el tiempo 1.0 para E4P_AMINO_ACIDS
Se encontró el ciclo [4, 13, 2, 0] en el tiempo 1.0 para E4P_AMINO_ACIDS
Se encontró el ciclo [6, 3, 1, 0] en el tiempo 1.0 para E4P_AMINO_ACIDS
Se encontró el ciclo [13, 14, 10, 2] en el tiempo 1.0 para E4P_AMINO_ACIDS
Se encontró el ciclo [6, 5, 4, 0] en el tiempo 1.0 para E4P_AMINO_ACIDS
Se encontró el ciclo [8, 12, 1, 0] en el tiempo 1.0 para E4P_AMINO_ACIDS
Terminó la ruta  E4P_AMINO_ACIDS
Se encontró el ciclo [8, 3, 5, 0] en el tiempo 1.0 para TCA
Se encontró el ciclo [9, 15, 2, 0] en el tiempo 1.0 para TCA
Se encontró el ciclo [5, 13, 2, 0] en el tiempo 1.0 para TCA
Se encontró el ciclo [5, 11, 1, 0] en el tiempo 1.0 para TCA
Terminó la ruta  TCA
Se encontró el ciclo [13, 7, 3, 1] en el tiempo 1.0 para 3PGA_AMINOACIDS
Se encontró el ciclo [5, 0, 4, 1] en el tiempo 1.0 para 3PGA_AMINOACIDS
Se encontró el ciclo [18, 16, 6, 2] en el tiempo 1.0 para 3PGA_AMINOACIDS
Se encontró el ciclo [9, 11, 5, 1] en el tiempo 1.0 para 3PGA_AMINOACIDS
Se encontró el ciclo [13, 15, 9, 1] en el tiempo 1.0 para 3PGA_AMINOACIDS
Se encontró el ciclo [14, 8, 3, 1] en el tiempo 1.0 para 3PGA_AMINOACIDS
Se encontró el ciclo [4, 12, 2, 3] en el tiempo 1.0 para 3PGA_AMINOACIDS
Se encontró el ciclo [13, 10, 4, 1] en el tiempo 1.0 para 3PGA_AMINOACIDS
Se encontró el ciclo [5, 6, 3, 1] en el tiempo 1.0 para 3PGA_AMINOACIDS
Terminó la ruta  3PGA_AMINOACIDS
Se encontró el ciclo [81, 15, 14, 6] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [11, 81, 6, 0] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [86, 53, 19, 8] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [45, 64, 37, 30] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [86, 53, 49, 12] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [36, 52, 40, 37, 30, 25] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [58, 26, 31, 12] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [75, 24, 30, 21] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [105, 46, 51, 16] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [82, 61, 76, 56] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [86, 56, 33, 12] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [43, 30, 24, 10] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [86, 82, 22, 12] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [85, 78, 39, 38] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [39, 78, 32, 1] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [85, 50, 60, 38] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [93, 80, 89, 100] en el tiempo 1.0 para PYR_THR_AA
Se encontró el ciclo [95, 80, 23, 72] en el tiempo 1.0 para PYR_THR_AA
se buscan ciclos en el tiempo 3.0 para PYR_THR_AA
Se encontró el ciclo [114, 112, 44, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [121, 102, 97, 80] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [115, 61, 111, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [44, 49, 35, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [67, 76, 35, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [73, 37, 46, 6] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [88, 31, 20, 30, 67, 46, 6, 4] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [115, 38, 44, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [99, 109, 93, 52] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [44, 67, 30, 12] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [133, 60, 56, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [133, 110, 115, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [133, 110, 26, 60] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [35, 33, 24, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [111, 17, 35, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [133, 97, 16, 1] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [99, 44, 46, 6] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [46, 1, 16, 6] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [66, 48, 51, 139] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [101, 87, 77, 22] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [101, 58, 34, 18] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [101, 71, 90, 18] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [105, 124, 90, 18] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [74, 47, 45, 28] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [101, 28, 74, 22] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [90, 21, 28, 18] en el tiempo 1.0 para ALPHAKETOGLUTARATE_AMINOACIDS
se buscan ciclos en el tiempo 3.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [84, 101, 53, 48] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [98, 101, 53, 43] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [68, 69, 37, 30] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [54, 86, 39, 20] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [48, 80, 42, 14] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [81, 17, 6, 0] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [20, 36, 38, 5, 12, 4] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [81, 74, 39, 4] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [37, 30, 11, 20] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [80, 49, 54, 20] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [27, 24, 50, 82, 46, 30, 11] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [94, 27, 75, 0] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [67, 87, 50, 24] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [80, 42, 36, 20] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [52, 40, 22, 18] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [65, 52, 35, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [94, 0, 92, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [81, 74, 75, 0] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [90, 42, 80, 25] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [43, 80, 35, 10] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [36, 85, 35, 20] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [67, 51, 48, 18] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [90, 45, 43, 25] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [56, 41, 4, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [92, 67, 24, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [81, 21, 20, 4] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [92, 81, 4, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [17, 29, 2, 6] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [39, 89, 7, 24] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [48, 80, 35, 18] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [64, 55, 24, 10] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [51, 53, 43, 25] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [81, 21, 22, 0] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [94, 28, 77, 32, 23, 36, 20, 4] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [24, 39, 4, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [92, 18, 35, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [41, 95, 37, 20] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [94, 11, 35, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [10, 97, 4, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [92, 18, 22, 0] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [94, 11, 22, 0] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [92, 67, 75, 0] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [35, 20, 4, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [43, 25, 24, 10] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [94, 27, 24, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [67, 51, 25, 24] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [65, 7, 24, 1] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [37, 69, 36, 20] en el tiempo 1.0 para OXALACETATE_AMINOACIDS
se buscan ciclos en el tiempo 3.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [79, 66, 63, 21] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [95, 89, 69, 11] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [34, 36, 24, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [105, 104, 72, 7] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [99, 35, 6, 0] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [88, 35, 44, 7] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [98, 55, 32, 0] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [59, 65, 3, 14] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [88, 62, 20, 7] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [84, 29, 81, 11] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [24, 45, 81, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [32, 84, 11, 0] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [90, 101, 75, 26] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [84, 47, 15, 11] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [44, 3, 14, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [41, 71, 39, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [31, 28, 34, 0] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [93, 80, 81, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [93, 23, 73, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [101, 91, 73, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [84, 103, 59, 11] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [1, 29, 81, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [97, 101, 24, 10] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [93, 92, 14, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [24, 64, 15, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [95, 67, 59, 11] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [100, 23, 30, 10] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [72, 23, 51, 7] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [93, 95, 11, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [31, 75, 6, 0] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [32, 1, 6, 0] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [73, 2, 1, 6] en el tiempo 2.0 para PYR_THR_AA
Se encontró el ciclo [47, 27, 41, 15] en el tiempo 2.0 para PYR_THR_AA
Terminó la ruta  PYR_THR_AA
Se encontró el ciclo [89, 64, 59, 136, 96] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [98, 81, 139, 66] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [107, 120, 59, 39] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [77, 117, 39, 28] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [143, 122, 66, 25] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [106, 93, 0, 143, 18] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [86, 81, 98, 122, 0, 44] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [116, 30, 20, 11] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [117, 36, 38, 12] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [59, 26, 36, 39] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [122, 7, 41, 0] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [64, 97, 7, 68] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [10, 17, 67, 4] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [23, 64, 97, 9] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [107, 98, 122, 143, 18] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [20, 31, 15, 11] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [121, 133, 35, 2] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [126, 59, 39, 21] en el tiempo 2.0 para ALPHAKETOGLUTARATE_AMINOACIDS
se buscan ciclos en el tiempo 4.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [104, 73, 75, 0] en el tiempo 2.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [47, 93, 31, 6] en el tiempo 2.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [66, 58, 34, 6] en el tiempo 2.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [93, 79, 40, 31] en el tiempo 2.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [102, 13, 68, 28] en el tiempo 2.0 para OXALACETATE_AMINOACIDS
Se encontró el ciclo [58, 13, 60, 34] en el tiempo 2.0 para OXALACETATE_AMINOACIDS
Terminó la ruta  OXALACETATE_AMINOACIDS
Se encontró el ciclo [106, 91, 36, 4] en el tiempo 3.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [75, 83, 6, 4] en el tiempo 3.0 para ALPHAKETOGLUTARATE_AMINOACIDS
Terminó la ruta  ALPHAKETOGLUTARATE_AMINOACIDS

In [24]:
resum=get_resum_df(df_by_pathway,representative_genomes,names,complex_pathways,holes_with_names)
resum

/opt/conda/envs/TDA/lib/python3.7/site-packages/pandas/core/internals/blocks.py:937: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_value = np.asarray(value)

,num_columnas,num_hoyos,ciclos,ciclos por genero,duración hoyos
R5P_AMINOACIDS,5,8,"[[Pseudomonas borbori DSM17834, Pseudomonas gu...","[[Pseudomonas, Pseudomonas, [Pseudomonas, Pseu...",[1.0]
Glycolysis,3,2,"[[[Pseudomonas fulva 12-X NC_015556.1, Pseudom...","[[[Pseudomonas, Pseudomonas, Pseudomonas, Pseu...",[1.0]
E4P_AMINO_ACIDS,7,6,"[[[Pseudomonas umsongensis 20MFCvi1.1 ARIW01, ...","[[[Pseudomonas, Pseudomonas, Pseudomonas, Pseu...",[1.0]
OXALACETATE_AMINOACIDS,5,54,"[[[Pseudomonas xinjiangensis NRRL B-51270, Pse...","[[[Pseudomonas, Pseudomonas], Pseudomonas, [Ps...",[1.0]
TCA,3,4,"[[[Pseudomonas sp. 20_bn CCSF01, Pseudomonas c...","[[[Pseudomonas, Pseudomonas, Pseudomonas, Pseu...",[1.0]
ALPHAKETOGLUTARATE_AMINOACIDS,12,46,"[[Pseudomonas kilonensis JZXC01, [Pseudomonas ...","[[Pseudomonas, [Pseudomonas, Pseudomonas], Pse...",[1.0]
polyketide,1,0,[],[],[]
3PGA_AMINOACIDS,2,9,"[[Pseudomonas salegens CECT8338, Pseudomonas c...","[[Pseudomonas, Pseudomonas, [Pseudomonas, Pseu...",[1.0]
PYR_THR_AA,6,51,[[Pseudomonas syringae pv. Avellanae str. Ispa...,"[[Pseudomonas, [Pseudomonas, Pseudomonas], [Ps...",[1.0]
calcium-dependent-antibiotic,1,0,[],[],[]

In [25]:
generos=set()
for i in traduced_df(df_by_pathway['R5P_AMINOACIDS'],names).index:
    generos.add(i.split(' ')[0])
df_count_genomes=pd.DataFrame(index=generos)
df_count_genomes['conteo']=0
for path in resum.index:
    ciclos_path=resum.loc[path,'ciclos por genero']
    for cic in ciclos_path:
        for vert in cic:
            if type(vert)==str:
                df_count_genomes.loc[vert,'conteo']=df_count_genomes.loc[vert,'conteo']+1
            else:
                for i in vert:
                    df_count_genomes.loc[i,'conteo']=df_count_genomes.loc[i,'conteo']+1
(df_count_genomes.sort_values(by='conteo',ascending=False)/df_count_genomes.sum())*100

                conteo
Pseudomonas  99.587405
pseudomonas   0.412595

In [26]:
generos=set()
for i in traduced_df(df_by_pathway['R5P_AMINOACIDS'],names).index:
    generos.add(i.split(' ')[0])
df_count_genomes=pd.DataFrame(index=traduced_df(df_by_pathway['R5P_AMINOACIDS'],names).index)
df_count_genomes['conteo']=0
for path in resum.index:
    ciclos_path=resum.loc[path,'ciclos']
    for cic in ciclos_path:
        for vert in cic:
            if type(vert)==str:
                df_count_genomes.loc[vert,'conteo']=df_count_genomes.loc[vert,'conteo']+1
            else:
                for i in vert:
                    df_count_genomes.loc[i,'conteo']=df_count_genomes.loc[i,'conteo']+1
df_count_genomes.sort_values(by='conteo',ascending=False)

                                                conteo
R5P_AMINOACIDS
Pseudomonas aeruginosa str. Stone 130 AQFN01        40
Pseudomonas denitrificans ATCC 13867 NC_020829      38
Pseudomonas aeruginosa CCVU01                       37
Pseudomonas aeruginosa JYGC02                       37
Pseudomonas aeruginosa atcc 15442 AYUC01            36
...                                                ...
Pseudomonas coronafaciens JSED01                     9
Pseudomonas xinjiangensis NRRL B-51270               8
Pseudomonas tuomuerensis JCM 14085                   8
Pseudomonas gingeri ncppb 3146 AKBP01                7
Pseudomonas indica NBRC 103045                       0

[216 rows x 1 columns]

In [29]:
long=[]
for k in resum.index:
    for i in resum.loc[k,'ciclos']:
        long.append(len(i))
print(set(long))
long.count(6)

{4, 5, 6, 7, 8}

3

<h2>Se ven los elementos que hacen el hoyo</h2>

In [18]:
df_pathway_make_hole=get_df_by_pathway_make_hole_droped_cols(df_by_pathway_drop_duplicate,holes_with_names)
df_count_genes_participation=pd.DataFrame()
for path in df_pathway_make_hole.keys():
    print('los genes que participan en los 1-hoyos para',path,'son:')
    genes=[]
    for df in df_pathway_make_hole[path]:
        genes.extend(list(df.columns))
    set_count_genes=set()
    for gen in genes:
        df_count_genes_participation.loc[gen,'conteo']=genes.count(gen)
        df_count_genes_participation.loc[gen,'ruta']=path
        set_count_genes.add(gen+':'+str(genes.count(gen)))
    print(str(set_count_genes))

los genes que participan en los 1-hoyos para R5P_AMINOACIDS son:
{'phosphoribosyl_isomerase_A:3', 'ribosephosphate_pyrophosphokinase:5', 'imidazole_glycerol_phosphate_synthase_H:6', 'histidinol_dehydrogenase:2'}
los genes que participan en los 1-hoyos para Glycolysis son:
{'Pyruvate_kinase:2', 'enolase:2'}
los genes que participan en los 1-hoyos para E4P_AMINO_ACIDS son:
{'Tryptophan_synthase_alpha:1', '3_dehydroquinate_synthase:3', 'Anthranilate_synthase_component_1:5', 'Indole3glycerol_phosphate_synthase:2', 'Tryptophan_synthase_beta:1'}
los genes que participan en los 1-hoyos para OXALACETATE_AMINOACIDS son:
{'diaminopimelate_decarboxylase:22', 'Threonine_synthase:10', 'Aspartate_transaminase:36', 'dihydropicolinate_synthase:37', 'argininosuccinate_lyase:14'}
los genes que participan en los 1-hoyos para TCA son:
{'Citrate_synthase:1', 'fumarate_hydratase:4', 'fumarate_reductase_ironsulfur_subunit:3'}
los genes que participan en los 1-hoyos para ALPHAKETOGLUTARATE_AMINOACIDS son:
{'N_acetylglutamate_synthase:1', 'Acetylglutamate_kinase:7', 'Glutamate_5_semialdehyde_dehydrogenase:4', 'glutamate_synthase:15', 'N_acetyl_gamma_glutamyl_phosphate_reductase:1', 'Acetylornithine_aminotransferase:38', 'Ornithine_carbamoyltransferase:8', 'Glutamine_synthetase:33', 'glutamate_dehydrogenase:10', 'Glutamine_2_oxoglutarate_aminotransferase:9'}
los genes que participan en los 1-hoyos para polyketide son:
set()
los genes que participan en los 1-hoyos para 3PGA_AMINOACIDS son:
{'glycine_hydroxymethyltransferase:9', 'Cysteine_synthase:9'}
los genes que participan en los 1-hoyos para PYR_THR_AA son:
{'Dihydroxiacid_dehydratase:32', 'Acetolactate_synthase_large:36', 'Acetolactate_synthase_large_subunit:35', '3isopropylmalate_dehydrogenase:29', 'isopropylmalate_isomerase_large_subunit:15'}
los genes que participan en los 1-hoyos para calcium-dependent-antibiotic son:
set()

In [20]:
total=df_count_genes_participation.sum()['conteo']
df_count_genes_participation.to_csv('3.csv')
df_count_genes_participation.sort_values(by='conteo',ascending=False)

,conteo,ruta
Acetylornithine_aminotransferase,38.0,ALPHAKETOGLUTARATE_AMINOACIDS
dihydropicolinate_synthase,37.0,OXALACETATE_AMINOACIDS
Acetolactate_synthase_large,36.0,PYR_THR_AA
Aspartate_transaminase,36.0,OXALACETATE_AMINOACIDS
Acetolactate_synthase_large_subunit,35.0,PYR_THR_AA
Glutamine_synthetase,33.0,ALPHAKETOGLUTARATE_AMINOACIDS
Dihydroxiacid_dehydratase,32.0,PYR_THR_AA
3isopropylmalate_dehydrogenase,29.0,PYR_THR_AA
diaminopimelate_decarboxylase,22.0,OXALACETATE_AMINOACIDS
glutamate_synthase,15.0,ALPHAKETOGLUTARATE_AMINOACIDS
isopropylmalate_isomerase_large_subunit,15.0,PYR_THR_AA
argininosuccinate_lyase,14.0,OXALACETATE_AMINOACIDS
Threonine_synthase,10.0,OXALACETATE_AMINOACIDS
glutamate_dehydrogenase,10.0,ALPHAKETOGLUTARATE_AMINOACIDS
glycine_hydroxymethyltransferase,9.0,3PGA_AMINOACIDS
Cysteine_synthase,9.0,3PGA_AMINOACIDS
Glutamine_2_oxoglutarate_aminotransferase,9.0,ALPHAKETOGLUTARATE_AMINOACIDS
Ornithine_carbamoyltransferase,8.0,ALPHAKETOGLUTARATE_AMINOACIDS
Acetylglutamate_kinase,7.0,ALPHAKETOGLUTARATE_AMINOACIDS
imidazole_glycerol_phosphate_synthase_H,6.0,R5P_AMINOACIDS
ribosephosphate_pyrophosphokinase,5.0,R5P_AMINOACIDS
Anthranilate_synthase_component_1,5.0,E4P_AMINO_ACIDS
fumarate_hydratase,4.0,TCA
Glutamate_5_semialdehyde_dehydrogenase,4.0,ALPHAKETOGLUTARATE_AMINOACIDS
fumarate_reductase_ironsulfur_subunit,3.0,TCA
3_dehydroquinate_synthase,3.0,E4P_AMINO_ACIDS
phosphoribosyl_isomerase_A,3.0,R5P_AMINOACIDS
Indole3glycerol_phosphate_synthase,2.0,E4P_AMINO_ACIDS
enolase,2.0,Glycolysis
Pyruvate_kinase,2.0,Glycolysis
histidinol_dehydrogenase,2.0,R5P_AMINOACIDS
N_acetyl_gamma_glutamyl_phosphate_reductase,1.0,ALPHAKETOGLUTARATE_AMINOACIDS
Tryptophan_synthase_beta,1.0,E4P_AMINO_ACIDS
Tryptophan_synthase_alpha,1.0,E4P_AMINO_ACIDS
N_acetylglutamate_synthase,1.0,ALPHAKETOGLUTARATE_AMINOACIDS
Citrate_synthase,1.0,TCA

In [12]:
traduced_df(df_pathway_make_hole['R5P_AMINOACIDS'][0],names)

,imidazoleglycerol_phosphate_dehydratase,histidinol_phosphatase,phosphoribosyl_AMP_cyclohydrolase,ribosephosphate_pyrophosphokinase,ATP_phosphoribosyltransferase,imidazole_glycerol_phosphate_synthase_H,phosphoribosyl_isomerase_A,histidinol_dehydrogenase,histidinolphosphate_aminotransferase
R5P_AMINOACIDS,,,,,,,,,
Serinicoccus sp. CNJ-927 CNJ-927,1.0,1.0,1.0,1.0,0.0,1.0,2,1.0,1.0
Ornithinimicrobium sp. na,1.0,1.0,0.0,0.0,0.0,2.0,2,1.0,1.0
Ornithinimicrobium humiphilum DSM 12362,1.0,1.0,0.0,1.0,1.0,2.0,2,1.0,2.0
Serinicoccus chungangensis CD08_5,1.0,1.0,1.0,1.0,1.0,2.0,2,1.0,2.0

<h2>Se buscan uno hoyos pero al separar por genero y ruta metabólica</h2>

In [13]:
df_by_genus_pathway,df_by_genus_pathway_drop_duplicate,representative_genomes_genus_pathway=get_df_by_genus_pathway(df_by_pathway,names)
complex_genus_pathways=get_complex_by_pathways(df_by_genus_pathway_drop_duplicate)

In [14]:
traduced_df(df_by_genus_pathway['Serinicoccus_ALPHAKETOGLUTARATE_AMINOACIDS'],names)

,Pyrroline-5-carboxylate_reductase,argininosuccinate_lyase,Glutamine_synthetase,Argininosuccinate,glutamate,Glutamate_5_kinase,Glutamine_2-oxoglutarate,Glutamate-5-semialdehyde_dehydrogenase,Ornithine_carbamoyltransferase,glutamate_synthase,Acetylornithine_aminotransferase
Serinicoccus_ALPHAKETOGLUTARATE_AMINOACIDS,,,,,,,,,,,
Serinicoccus chungangensis CD08_5,1.0,1.0,3,1.0,0.0,1.0,1.0,1.0,1.0,1.0,6.0
Serinicoccus hydrothermalis JLT9,1.0,1.0,3,1.0,0.0,1.0,1.0,1.0,1.0,2.0,8.0
Serinicoccus sp. CUA-874 CUA-874,1.0,1.0,4,1.0,0.0,1.0,1.0,1.0,1.0,1.0,5.0
Serinicoccus sp. CNJ-927 CNJ-927,1.0,1.0,4,1.0,0.0,0.0,1.0,1.0,1.0,1.0,7.0

In [15]:
holes_genus_no_names,holes_genus_with_names,holes_genus_per_filt_lvl=get_holes_by_pathways(complex_genus_pathways,df_by_genus_pathway_drop_duplicate)

se buscan ciclos en el tiempo 3.0 para Ornithinimicrobium_3PGA_AMINOACIDS
Se encontró el ciclo [10, 1, 5, 2] en el tiempo 2.0 para Ornithinimicrobium_3PGA_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Ornithinimicrobium_PPP
Se encontró el ciclo [11, 3, 5, 2] en el tiempo 1.0 para Ornithinimicrobium_PPP
se buscan ciclos en el tiempo 6.0 para Ornithinimicrobium_OXALACETATE_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Ornithinimicrobium_ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [15, 10, 6, 1] en el tiempo 1.0 para Ornithinimicrobium_ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [15, 4, 2, 1] en el tiempo 1.0 para Ornithinimicrobium_ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [0, 14, 16, 2] en el tiempo 5.0 para Ornithinimicrobium_OXALACETATE_AMINOACIDS
Se encontró el ciclo [4, 7, 5, 2] en el tiempo 5.0 para Ornithinimicrobium_OXALACETATE_AMINOACIDS

In [16]:
resum_genus=get_resum_df(df_by_genus_pathway,representative_genomes_genus_pathway,names,complex_genus_pathways,holes_genus_with_names)
resum_genus

/opt/conda/envs/TDA/lib/python3.7/site-packages/pandas/core/internals/blocks.py:937: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_value = np.asarray(value)

,num_columnas,num_hoyos,ciclos,ciclos por genero,duración hoyos
Serinicoccus_Glycolysis,10,0,[],[],[]
Ornithinimicrobium_Glycolysis,10,0,[],[],[]
Serinicoccus_3PGA_AMINOACIDS,5,0,[],[],[]
Ornithinimicrobium_3PGA_AMINOACIDS,5,1,"[[Ornithinimicrobium sp. na, Ornithinimicrobiu...","[[Ornithinimicrobium, Ornithinimicrobium, [Orn...",[1.0]
Serinicoccus_TCA,11,0,[],[],[]
Ornithinimicrobium_TCA,11,0,[],[],[]
Serinicoccus_PPP,8,0,[],[],[]
Ornithinimicrobium_PPP,8,1,"[[Ornithinimicrobium cerasi USBA17B2, [Ornithi...","[[Ornithinimicrobium, [Ornithinimicrobium, Orn...",[1.0]
Serinicoccus_R5P_AMINOACIDS,9,0,[],[],[]
Ornithinimicrobium_R5P_AMINOACIDS,9,0,[],[],[]
Serinicoccus_﻿Glycolysis,1,0,[],[],[]
Ornithinimicrobium_﻿Glycolysis,1,0,[],[],[]
Serinicoccus_PYR_THR_AA,10,0,[],[],[]
Ornithinimicrobium_PYR_THR_AA,10,0,[],[],[]
Serinicoccus_E4P_AMINO_ACIDS,17,0,[],[],[]
Ornithinimicrobium_E4P_AMINO_ACIDS,17,0,[],[],[]
Serinicoccus_OXALACETATE_AMINOACIDS,16,0,[],[],[]
Ornithinimicrobium_OXALACETATE_AMINOACIDS,16,2,"[[Ornithinimicrobium pratense W204, Ornithinim...","[[Ornithinimicrobium, Ornithinimicrobium, Orni...",[1.0]
Serinicoccus_ALPHAKETOGLUTARATE_AMINOACIDS,11,0,[],[],[]
Ornithinimicrobium_ALPHAKETOGLUTARATE_AMINOACIDS,11,2,"[[Ornithinimicrobium cerasi USBA17B2, Ornithin...","[[Ornithinimicrobium, Ornithinimicrobium, Orni...",[1.0]

<h1>Para obtener la información de los 1-hoyos de la ruta R5P AMINOACIDS:</h1>

In [21]:
R5P_df_by_pathway={'R5P_AMINOACIDS':df_by_pathway['R5P_AMINOACIDS']}
R5P_df_by_pathway_drop_duplicate={'R5P_AMINOACIDS':df_by_pathway_drop_duplicate['R5P_AMINOACIDS']}
R5P_representative_genomes={'R5P_AMINOACIDS':representative_genomes['R5P_AMINOACIDS']}
R5P_complex_pathways={'R5P_AMINOACIDS':complex_pathways['R5P_AMINOACIDS']}

In [22]:
R5P_holes_no_names,R5P_holes_with_names,R5P_holes_per_filt_lvl=get_holes_by_pathways(R5P_complex_pathways,R5P_df_by_pathway_drop_duplicate)

se buscan ciclos en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [9, 12, 7, 2] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [5, 14, 2, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [24, 15, 3, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [24, 23, 8, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [8, 25, 3, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [2, 10, 1, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [4, 9, 2, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [5, 6, 3, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Terminó la ruta  R5P_AMINOACIDS

In [20]:
get_resum_df(R5P_df_by_pathway,R5P_representative_genomes,names,R5P_complex_pathways,R5P_holes_with_names)

/opt/conda/envs/TDA/lib/python3.7/site-packages/pandas/core/internals/blocks.py:937: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_value = np.asarray(value)

,num_columnas,num_hoyos,ciclos,ciclos por genero,duración hoyos
R5P_AMINOACIDS,9,1,"[[Serinicoccus sp. CNJ-927 CNJ-927, Ornithinim...","[[Serinicoccus, Ornithinimicrobium, [Ornithini...",[1.0]

<h3>Género por R5P</h3>

In [21]:
R5P_df_by_genus_pathway,R5P_df_by_genus_pathway_drop_duplicate,R5P_representative_genomes_genus_pathway=get_df_by_genus_pathway(R5P_df_by_pathway,names)
R5P_complex_genus_pathways=get_complex_by_pathways(R5P_df_by_genus_pathway_drop_duplicate)

In [22]:
R5P_holes_genus_no_names,R5P_holes_genus_with_names,R5P_holes_genus_per_filt_lvl=get_holes_by_pathways(R5P_complex_genus_pathways,R5P_df_by_genus_pathway_drop_duplicate)

In [24]:
get_resum_df(R5P_df_by_genus_pathway,R5P_representative_genomes_genus_pathway,names,R5P_complex_genus_pathways,R5P_holes_genus_with_names)

,num_columnas,num_hoyos,ciclos,ciclos por genero,duración hoyos
Serinicoccus_R5P_AMINOACIDS,9,0,[],[],[]
Ornithinimicrobium_R5P_AMINOACIDS,9,0,[],[],[]